"""Diamond Assistant — chat UI over app/assistant.py. Every answer is
generated by Claude calling this site's own db.py query functions (see
that module's docstring); nothing here invents a stat."""
import sys
from pathlib import Path

import streamlit as st

sys.path.append(str(Path(__file__).resolve().parent.parent))
import assistant

st.set_page_config(page_title="Diamond Assistant | Diamond Metrics", layout="wide")
st.title("Diamond Assistant")
st.caption(
    "Ask a stat question in plain language — leaders, cross-references, one "
    "player's line. Answers come from this site's own MLB database, not the "
    "model's memory."
)

if not assistant.available():
    st.warning(
        "The Diamond Assistant needs an Anthropic API key to run. Add "
        "`ANTHROPIC_API_KEY` under **Settings → Secrets** on Streamlit "
        "Community Cloud, or as a local environment variable / "
        "`.streamlit/secrets.toml` entry for development."
    )
    st.stop()

if "assistant_messages" not in st.session_state:
    st.session_state.assistant_messages = []

for msg in st.session_state.assistant_messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

if prompt := st.chat_input("e.g. \"Who leads the league in wRC+? Show me their ISO too.\""):
    st.session_state.assistant_messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)
    with st.chat_message("assistant"):
        with st.spinner("Looking it up..."):
            answer = assistant.ask(prompt, st.session_state.assistant_messages[:-1])
        st.markdown(answer)
    st.session_state.assistant_messages.append({"role": "assistant", "content": answer})

if st.session_state.assistant_messages and st.button("Clear conversation"):
    st.session_state.assistant_messages = []
    st.rerun()
